- hosts: kubernetes
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - { role: commons }
    - { role: containerd }
    - { role: kubernetes }

- hosts: masters
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - { role: masters }

- hosts: nodes
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - { role: nodes }